language: node_js
node_js:
  - "12"
dist: trusty
addons:
  chrome: stable
services:
  - mongodb
  - redis
cache:
  yarn: true
  directories:
    - node_modules
    - client/node_modules
before_install:
  - npm install -g yarn@1.22.19
  - sudo apt-get update
  - sudo apt-get install -y libgbm-dev
install:
  - yarn install --frozen-lockfile
  - yarn build
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - nohup yarn start &
  - sleep 10
  - yarn test:ci
