language: node_js
node_js:
  - "12"
dist: trusty
addons:
  chrome: stable
services:
  - mongodb
  - redis
  - xvfb
cache:
  yarn: true
  directories:
    - node_modules
    - client/node_modules
before_install:
  - npm install -g yarn@1.22.19
install:
  - yarn install --frozen-lockfile
  - yarn run build
script:
  - nohup yarn run start &
  - sleep 10
  - yarn run test:ci
