language: node_js
node_js:
  - "12"
dist: trusty
sudo: false  
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  yarn: true
  directories:
    - node_modules
    - client/node_modules
before_install:
  - npm install -g yarn@1.22.19
install:
  - yarn install --frozen-lockfile
  - yarn run build
script:
  - nohup yarn run start &
  - sleep 10
  - yarn run test
