language: node_js
node_js:
  - "12"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  yarn: true
  directories:
    - node_modules
    - client/node_modules
install:
  - yarn install --frozen-lockfile
  - yarn run build
script:
  - nohup yarn run start &
  - sleep 10
  - yarn run test
