language: node_js
node_js:
  - "12"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  yarn: true
  directories:
    - node_modules
    - client/node_modules
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.19
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install
  - yarn build
script:
  - nohup yarn start &
  - sleep 3
  - yarn test
